# Generated by Django 2.1.3 on 2018-11-08 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('path', models.TextField(null=True)),
                ('params', models.TextField(null=True)),
                ('generator_class', models.TextField()),
                ('policies', models.TextField()),
                ('classes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DatasetRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.TextField()),
                ('path', models.TextField()),
                ('override_classes', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='tlabel_backend.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(db_index=True, null=True)),
                ('message_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('username', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TGBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('name', models.TextField()),
                ('botname', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='labeler',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tlabel_backend.TGBot'),
        ),
        migrations.AddField(
            model_name='label',
            name='labeler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='tlabel_backend.Labeler'),
        ),
        migrations.AddField(
            model_name='label',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='tlabel_backend.DatasetRow'),
        ),
        migrations.AlterUniqueTogether(
            name='labeler',
            unique_together={('bot', 'tg_id')},
        ),
        migrations.AlterUniqueTogether(
            name='datasetrow',
            unique_together={('row_id', 'dataset')},
        ),
    ]
